title: 尤点儿东西
description: 总会用到的吧~~~.
show_downloads: false
google_analytics:
theme: jekyll-theme-merlot

# Markdown配置
markdown: kramdown

# 分页（可选）
paginate: 5
paginate_path: "/page:num/"

# 时区
timezone: Asia/Shanghai
